# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  newPkgVersion: "--------"

steps:
- bash: |
    FOO="some value"
    echo "##vso[task.setvariable variable=newPkgVersion]$FOO"

  # Using the $() syntax, the value is replaced inside Azure Pipelines before being submitted to the script task
- bash: |
    echo "$(newPkgVersion)"

- task: NugetVersionUpdater@1
  inputs:
    packageName: 'MedPark.Common'
    maxIncrement: 10
    pipelineVariable: 'newPkgVersion'
  enabled: false


