version: "3.5"

services:
  medpark-api:
    image: medpark-api
    ports:
     - 8000:5000
    networks:
      - medpark
      
  customers:
    image: customers
    ports:
      - 8001:5001
    networks:
      - medpark
      
  medpark-practice:
    image: medpark-practice
    ports:
      - 8002:5002
    networks:
      - medpark
      
  medpark-bookings:
    image: medpark-bookings
    ports:
      - 8003:5003
    networks:
      - medpark
      
  medpark-catalog:
    image: medpark-catalog
    ports:
      - 8004:5004
    networks:
      - medpark
      
  medpark-order:
    image: medpark-order
    ports:
      - 8005:5005
    networks:
      - medpark

networks:
  medpark:
    name: medpark-network
    external: true