version: "3.5"

services:
  api:
    image: medpark-api
    container_name: medpark-api
    ports:
      - 5000:5000
    networks:
      - medpark

networks:
  medpark:
    name: medpark-network
    external: true