version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - medpark
    # network_mode: host
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

networks:
  medpark:
    name: medpark-network

volumes:
  rabbitmq:
    driver: local