@apiUrl = https://localhost:44308/api/customers
@customerId = 888E9C20-0401-4D6B-BC39-4F5F203C8A5A


### Get customer by id
GET {{apiUrl}}/{{customerId}}


### Get customer addresses
GET {{apiUrl}}/GetAddreses/{{customerId}}


### Add customer address
POST {{apiUrl}}/CreateAddress
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000000",
  "addressLine1": "212 Boshoff street",
  "addressLine2": "Nieuwe Muckleneuk",
  "addressLine3": "Pretoria",
  "addressType": 1,
  "postalCode": "0181",
  "userId": "{{customerId}}"
}