// <auto-generated />
using System;
using MedPark.MedicalPractice;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedPark.MedicalPractice.Migrations
{
    [DbContext(typeof(MedicalPracticeDbContext))]
    [Migration("20190904151717_addDataTypeToTimeSpen")]
    partial class addDataTypeToTimeSpen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.AcceptedMedicalScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DateEffective");

                    b.Property<DateTime>("DateEnd");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("PracticeId");

                    b.Property<Guid>("SchemeId");

                    b.Property<string>("SchemeName");

                    b.HasKey("Id");

                    b.ToTable("AcceptedMedicalScheme");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("AddressLine3");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("PostalCode");

                    b.Property<Guid>("PracticeId");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.AppointmentAccepted", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppointmentTypeId");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("Enabled");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("SpecialistId");

                    b.HasKey("Id");

                    b.ToTable("AppointmentAccepted");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.AppointmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AppointmentType");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Mobile");

                    b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.Institute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Institute");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.MedicalScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("SchemeName");

                    b.HasKey("Id");

                    b.ToTable("MedicalScheme");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.OperatingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<TimeSpan?>("FridayClose");

                    b.Property<TimeSpan?>("FridayOpen");

                    b.Property<DateTime>("Modified");

                    b.Property<TimeSpan?>("MondayClose");

                    b.Property<TimeSpan?>("MondayOpen");

                    b.Property<Guid?>("PracticeId");

                    b.Property<TimeSpan?>("PublicHolidayClose");

                    b.Property<TimeSpan?>("PublicHolidayOpen");

                    b.Property<TimeSpan?>("SaturdayClose");

                    b.Property<TimeSpan?>("SaturdayOpen");

                    b.Property<Guid?>("SpecialistId");

                    b.Property<TimeSpan?>("SundayClose");

                    b.Property<TimeSpan?>("SundayOpen");

                    b.Property<TimeSpan?>("ThursdayClose");

                    b.Property<TimeSpan?>("ThursdayOpen");

                    b.Property<TimeSpan?>("TuesdayClose");

                    b.Property<TimeSpan?>("TuesdayOpen");

                    b.Property<TimeSpan?>("WednesdayClose");

                    b.Property<TimeSpan?>("WednesdayOpen");

                    b.HasKey("Id");

                    b.ToTable("OperatingHours");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.PendingRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("LastName");

                    b.Property<string>("Mobile");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("OTP");

                    b.Property<Guid>("PracticeId");

                    b.HasKey("Id");

                    b.ToTable("PendingRegistration");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.Practice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("LocationLatitude");

                    b.Property<string>("LocationLongitude");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("PracticeName");

                    b.Property<string>("Slogan");

                    b.Property<string>("TelephonePrimary");

                    b.Property<string>("TelephoneSecondary");

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.ToTable("Practice");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.Qualifications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CredentialId");

                    b.Property<Guid>("InstituteId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("QualificationName");

                    b.Property<DateTime>("YearObtained");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.Specialist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<TimeSpan>("AppointmentDuration");

                    b.Property<string>("Avatar");

                    b.Property<string>("Cellphone");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsVerfied");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("PracticeId");

                    b.Property<Guid?>("SpecialityId");

                    b.Property<string>("Surname");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Specialist");
                });

            modelBuilder.Entity("MedPark.MedicalPractice.Domain.Speciality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Speciality");
                });
#pragma warning restore 612, 618
        }
    }
}
