FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /app
COPY . .
RUN dotnet publish . -c Release -o out

FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /app
COPY --from=build /app/out .
ENV ASPNETCORE_URLS http://*:5007
ENV ASPNETCORE_ENVIRONMENT docker
EXPOSE 8007
ENTRYPOINT dotnet MedPark.Payment.dll