// <auto-generated />
using System;
using MedPark.Payment;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedPark.Payment.Migrations
{
    [DbContext(typeof(PaymentDBContext))]
    [Migration("20190805144021_updatedColumnTypes")]
    partial class updatedColumnTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MedPark.Payment.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CustomerId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("MedPark.Payment.Domain.CustomerPaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CustomerId");

                    b.Property<DateTime>("Modified");

                    b.Property<DateTime?>("PaymentCardExpiry");

                    b.Property<string>("PaymentCardNumber");

                    b.Property<string>("PaymentCardSecurityCode");

                    b.Property<int>("PaymentCardType");

                    b.Property<Guid>("PaymentTypeId");

                    b.HasKey("Id");

                    b.ToTable("CustomerPaymentMethod");
                });

            modelBuilder.Entity("MedPark.Payment.Domain.OrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CustomerId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("OrderId");

                    b.Property<Guid?>("OrderPaymentTypeId");

                    b.Property<decimal>("OrderTotal");

                    b.Property<int>("PaymentStatus");

                    b.HasKey("Id");

                    b.ToTable("OrderPayment");
                });

            modelBuilder.Entity("MedPark.Payment.Domain.PaymentStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PaymentStatus");
                });

            modelBuilder.Entity("MedPark.Payment.Domain.PaymentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PaymentType");
                });
#pragma warning restore 612, 618
        }
    }
}
