# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(basket-proj-path)'

- task: DotNetCoreCLI@2
  displayName: 'Generate DB migration script for MedPark.Basket'
  inputs:
    command: custom
    custom: 'dotnet ef migrations script'
    arguments: '--project $(basket-proj-path) -i -o $(build.artifactstagingdirectory)\sql\MedPark.Basket_DB_Migrations.sql'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(basket-proj-path)'
    arguments: '-c Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
    publishLocation: 
