# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- dev
- master
- feature/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: 'src/MedPark.Common/MedPark.Common.csproj'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Set pipeline to use DotNet Core 3.1'
  inputs:
    version: '3.1.x'
    includePreviewVersions: false
  enabled: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(project)'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '-c Release'
  enabled: true

- task: NuGetAuthenticate@0
  displayName: 'Authnticate with Nuget'
  inputs:
    nuGetServiceConnections: 'MedParkNuGetFeed'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '$(project)'
    majorVersion: 1
    minorVersion: 5
    patchVersion: 0

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: push
    nuGetFeedType: external
  enabled: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
